name: YardRace
version: '${project.version}'
main: cc.yardpodcast.yardrace.Main
api-version: 1.20
commands:
  createline:
    description: Creates a line
    usage: /<command> <start/end/checkpoint>
  getboat:
    description: Gets a boat
    aliases: [b, boat, gboat, getb]